### ISSUE TITLE
Fıx To Struct

### ISSUE THREAD

**Issue by VB10** [EkoB4/Swift_Task#3]
https://github.com/EkoB4/Swift_Task/blob/87c9113a1f2e7b21c8c77deaa91678cbbc60cefb/List/fruitView.swift#L30

struct fruitsTypes : Identifiable {
    var id = UUID()
    var Fruitname : String
    var FruitPrice : Int
} X

struct FruitModel : Identifiable {
    let id = UUID()
    let name : String
    let price : Int
}

**Comment by EkoB4** [comment]
Names fixed .
